FROM node:8.9.1-alpine AS builder

RUN apk --no-cache add \
  bash \
  g++ \
  ca-certificates \
  lz4-dev \
  musl-dev \
  cyrus-sasl-dev \
  openssl-dev \
  make \
  python \
  git

WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm install

FROM node:8.9.1-alpine

RUN apk --no-cache add libsasl openssl lz4-libs bash

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules

COPY . /app

CMD npm run test
