version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  exporter:
    build: .
    volumes:
      - ./:/app
    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      PARITY_URL: http://parity-v2-parity.default.svc.cluster.local:8545/
      START_BLOCK: 1000000
    command: ["./wait-for-it.sh", "kafka:9092", "--", "npm", "start"]
