version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
  exporter:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      PARITY_URL: http://parity.stage.san:30954
      START_BLOCK: 1000000
    entrypoint: "/bin/sh"
    command: ["-c", "docker/wait_for_services.sh && npm start"]