version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: none
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
  exporter:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      NODE_URL: "${NODE_URL}"
      START_BLOCK: "${START_BLOCK}"
      KAFKA_TOPIC: "${KAFKA_TOPIC}"
      AVAX: "${AVAX}"
      GET_RECEIPTS_ENDPOINT: "${GET_RECEIPTS_ENDPOINT}"
      DRY_RUN: "${DRY_RUN}"
    entrypoint: "/bin/sh"
    command: ["-c", "docker/wait_for_services.sh && npm start"]
